x-shared-parameters: &shared-parameters
  env_file:
    - ../../.env
  restart: always
  networks:
    - default
    - common-network

x-db-dependency: &db-dependency
  depends_on:
    db:
      condition: service_started
  environment:
    - DB_HOST=db
    - REDIS_HOST=redis


volumes:
  db-data-2:
  pgadmin_data:
networks:
  common-network:
    external: true


services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data-2:/var/lib/postgresql/data/
    env_file:
      - ../../.env
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - 8090:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin/

  redis:
    image: redis:latest
    restart: unless-stopped
    command: >
      redis-server --requirepass ${REDIS_PASSWORD} --maxclients 1000
    ports:
      - "6379:6379"
    env_file:
      - ../../.env

  taskiq:
    <<: [*shared-parameters, *db-dependency]
    build:
      context: ../../backend
      dockerfile: Dockerfile
    command: sh /app/config/entrypoints/taskiq.sh

  taskiq-scheduler:
    <<: [*shared-parameters, *db-dependency]
    build:
      context: ../../backend
      dockerfile: Dockerfile
    command: sh /app/config/entrypoints/taskiq-scheduler.sh

  # app:
  #   <<: [*shared-parameters, *db-dependency]
  #   build:
  #     context: ../../backend
  #     dockerfile: Dockerfile
  #   command: sh /app/config/entrypoints/entrypoint.sh
  #   ports:
  #     - 8000:8000

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../backend/staticfiles:/var/html/static/:ro
      - ../../backend/media:/var/html/media/:ro
    ports:
      - "80:80"
    network_mode: host